using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace d2
{
    public struct MonsterData 
    {
        public string name;
        public string assetsSuffix;
        public string soundSuffix;
        public string trnFile;
        public MonsterAvailability availability;
        public int width;
        public int image;
        public bool hasSpecial;
        public bool hasSpecialSound;
        public int[] frames;
        public int[] rate;
        public int minDunLvl;
        public int maxDunLvl;
        public int level;
        public int hitPointsMinimum;
        public int hitPointsMaximum;
        public _mai_id ai;
        /**
        * @brief Denotes monster's abilities defined in @p monster_flag as bitflags
        * For usage, see @p MonstersData in monstdat.cpp
        */
        public int abilityFlags;
        public int intelligence;
        public int toHit;
        public int animFrameNum;
        public int minDamage;
        public int maxDamage;
        public int toHitSpecial;
        public int animFrameNumSpecial;
        public int minDamageSpecial;
        public int maxDamageSpecial;
        public int armorClass;
        public MonsterClass monsterClass;
        /** Using monster_resistance as bitflags */
        public int resistance;
        /** Using monster_resistance as bitflags */
        public int resistanceHell;
        public int selectionType; // TODO Create enum
        /** Using monster_treasure */
        public int treasure;
        public int exp;
    };

    public struct ItemData 
    {
        public item_drop_rate iRnd;
        public item_class iClass;
        public item_equip_type iLoc;
        public item_cursor_graphic iCurs;
        public ItemType itype;
        public unique_base_item iItemId;
        public string iName;
        public string iSName;
        public int iMinMLvl;
        public int iDurability;
        public int iMinDam;
        public int iMaxDam;
        public int iMinAC;
        public int iMaxAC;
        public int iMinStr;
        public int iMinMag;
        public int iMinDex;
        public ItemSpecialEffect iFlags; // ItemSpecialEffect as bit flags
        public item_misc_id iMiscId;
        public spell_id iSpell;
        public bool iUsable;
        public int iValue;

        public ItemData(item_drop_rate iRnd,
        item_class iClass,
        item_equip_type iLoc,
        item_cursor_graphic iCurs,
        ItemType itype,
        unique_base_item iItemId,
        string iName,
        string iSName,
        int iMinMLvl,
        int iDurability,
        int iMinDam,
        int iMaxDam,
        int iMinAC,
        int iMaxAC,
        int iMinStr,
        int iMinMag,
        int iMinDex,
        ItemSpecialEffect iFlags,
        item_misc_id iMiscId,
        spell_id iSpell,
        bool iUsable,
        int iValue)
        {
            this.iRnd = iRnd;
            this.iClass = iClass;
            this.iLoc = iLoc;
            this.iCurs = iCurs;
            this.itype = itype;
            this.iItemId = iItemId;
            this.iName = iName;
            this.iSName = iSName;
            this.iMinMLvl = iMinMLvl;
            this.iDurability = iDurability;
            this.iMinDam = iMinDam;
            this.iMaxDam = iMaxDam;
            this.iMinAC = iMinAC;
            this.iMaxAC = iMaxAC;
            this.iMinStr = iMinStr;
            this.iMinMag = iMinMag;
            this.iMinDex = iMinDex;
            this.iFlags = iFlags;
            this.iMiscId = iMiscId;
            this.iSpell = iSpell;
            this.iUsable = iUsable;
            this.iValue = iValue;
        }
    };

    public class d2Data
    {
        /** Contains the data related to each item ID. */
        public static readonly ItemData[] AllItemsList = {
            // clang-format off
        //_item_indexes        iRnd,          iClass,        iLoc,             iCurs,                             itype,                 iItemId,            iName,                             iSName,     iMinMLvl, iDurability, iMinDam, iMaxDam, iMinAC, iMaxAC, iMinStr, iMinMag, iMinDex, iFlags,                                           iMiscId,         iSpell,          iUsable, iValue
        /*IDI_GOLD       */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_GOLD,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_GOLD,                        ItemType.Gold,        unique_base_item.UITYPE_NONE,        "Gold",                        null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        true,         0 ),
        /*IDI_WARRIOR    */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_SHORT_SWORD,                 ItemType.Sword,       unique_base_item.UITYPE_NONE,        "Short Sword",                 null,           2,          20,       2,       6,      0,      0,      18,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       50 ),
        /*IDI_WARRSHLD   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_BUCKLER,                     ItemType.Shield,      unique_base_item.UITYPE_NONE,        "Buckler",                     null,           2,          10,       0,       0,      3,      3,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       50 ),
        /*IDI_WARRCLUB   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_CLUB,                        ItemType.Mace,        unique_base_item.UITYPE_SPIKCLUB,    "Club",                        null,           1,          20,       1,       6,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       20 ),
        /*IDI_ROGUE      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_BOW,                   ItemType.Bow,         unique_base_item.UITYPE_NONE,        "Short Bow",                   null,           1,          30,       1,       4,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      100 ),
        /*IDI_SORCERER   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_STAFF,                 ItemType.Staff,       unique_base_item.UITYPE_NONE,        "Short Staff of Mana",         null,           1,          25,       2,       4,      0,      0,       0,      20,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_STAFF,     spell_id.SPL_MANA,        false,      520 ),
        /*IDI_CLEAVER    */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_CLEAVER,                     ItemType.Axe,         unique_base_item.UITYPE_CLEAVER,     "Cleaver",                     null,          10,          10,       4,      24,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,     2000 ),
        /*IDI_SKCROWN    */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_THE_UNDEAD_CROWN,            ItemType.Helm,        unique_base_item.UITYPE_SKCROWN,     "The Undead Crown",            null,           0,          50,       0,       0,     15,     15,       0,       0,       0, ItemSpecialEffect.RandomStealLife,               item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,    10000 ),
        /*IDI_INFRARING  */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_RING,        item_cursor_graphic.ICURS_EMPYREAN_BAND,               ItemType.Ring,        unique_base_item.UITYPE_INFRARING,   "Empyrean Band",               null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,     8000 ),
        /*IDI_ROCK       */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_MAGIC_ROCK,                  ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Magic Rock",                  null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_OPTAMULET  */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_AMULET,      item_cursor_graphic.ICURS_OPTIC_AMULET,                ItemType.Amulet,      unique_base_item.UITYPE_OPTAMULET,   "Optic Amulet",                null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,     5000 ),
        /*IDI_TRING      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_RING,        item_cursor_graphic.ICURS_RING_OF_TRUTH,               ItemType.Ring,        unique_base_item.UITYPE_TRING,       "Ring of Truth",               null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,     1000 ),
        /*IDI_BANNER     */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_TAVERN_SIGN,                 ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Tavern Sign",                 null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_HARCREST   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_HARLEQUIN_CREST,             ItemType.Helm,        unique_base_item.UITYPE_HARCREST,    "Harlequin Crest",             null,           0,          15,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,       15 ),
        /*IDI_STEELVEIL  */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_VIEL_OF_STEEL,               ItemType.Helm,        unique_base_item.UITYPE_STEELVEIL,   "Veil of Steel",               null,           0,          60,       0,       0,     18,     18,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,        0 ),
        /*IDI_GLDNELIX   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_GOLDEN_ELIXIR,               ItemType.Misc,        unique_base_item.UITYPE_ELIXIR,      "Golden Elixir",               null,          15,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_ANVIL      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_ANVIL_OF_FURY,               ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Anvil of Fury",               null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_MUSHROOM   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BLACK_MUSHROOM,              ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Black Mushroom",              null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_BRAIN      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BRAIN,                       ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Brain",                       null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_FUNGALTM   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_FUNGAL_TOME,                 ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Fungal Tome",                 null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_SPECELIX   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SPECTRAL_ELIXIR,             ItemType.Misc,        unique_base_item.UITYPE_ELIXIR,      "Spectral Elixir",             null,          15,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SPECELIX,  spell_id.SPL_NULL,        false,        0 ),
        /*IDI_BLDSTONE   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BLOOD_STONE,                 ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Blood Stone",                 null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_MAPOFDOOM  */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_MAP_OF_THE_STARS,            ItemType.Misc,        unique_base_item.UITYPE_MAPOFDOOM,   "Cathedral Map",               null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_MAPOFDOOM, spell_id.SPL_NULL,        true,         0 ),
        /*IDI_EAR        */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_EAR_SORCERER,                ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Heart",                       null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_EAR,       spell_id.SPL_NULL,        false,        0 ),
        /*IDI_HEAL       */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_HEALING,           ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Healing",           null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_HEAL,      spell_id.SPL_NULL,        true,        50 ),
        /*IDI_MANA       */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_MANA,              ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Mana",              null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_MANA,      spell_id.SPL_NULL,        true,        50 ),
        /*IDI_IDENTIFY   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Identify",          null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_IDENTIFY,    true,       200 ),
        /*IDI_PORTAL     */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Town Portal",       null,           4,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_TOWN,        true,       200 ),
        /*IDI_ARMOFVAL   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_ARKAINES_VALOR,              ItemType.MediumArmor, unique_base_item.UITYPE_ARMOFVAL,    "Arkaine's Valor",             null,           0,          40,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,        0 ),
        /*IDI_FULLHEAL   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_FULL_HEALING,      ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Full Healing",      null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_FULLHEAL,  spell_id.SPL_NULL,        true,       150 ),
        /*IDI_FULLMANA   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_FULL_MANA,         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Full Mana",         null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_FULLMANA,  spell_id.SPL_NULL,        true,       150 ),
        /*IDI_GRISWOLD   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_BROAD_SWORD,                 ItemType.Sword,       unique_base_item.UITYPE_GRISWOLD,    "Griswold's Edge",             null,           8,          50,       4,      12,      0,      0,      40,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,      750 ),
        /*IDI_LGTFORGE   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_BOVINE,                      ItemType.HeavyArmor,  unique_base_item.UITYPE_BOVINE,      "Bovine Plate",                null,           0,          40,       0,       0,      0,      0,      50,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_UNIQUE,    spell_id.SPL_NULL,        false,        0 ),
        /*IDI_LAZSTAFF   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_STAFF_OF_LAZARUS,            ItemType.Misc,        unique_base_item.UITYPE_LAZSTAFF,    "Staff of Lazarus",            null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_RESURRECT  */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Resurrect",         null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_RESURRECT,   true,       250 ),
        /*IDI_OIL        */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_OIL,                         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Blacksmith Oil",              null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_OILBSMTH,  spell_id.SPL_NULL,        true,       100 ),
        /*IDI_SHORTSTAFF */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_STAFF,                 ItemType.Staff,       unique_base_item.UITYPE_NONE,        "Short Staff",                 null,           1,          25,       2,       4,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       20 ),
        /*IDI_BARDSWORD  */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_SHORT_SWORD,                 ItemType.Sword,       unique_base_item.UITYPE_NONE,        "Sword",                       null,           2,           8,       1,       5,      0,      0,      15,       0,      20, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       20 ),
        /*IDI_BARDDAGGER */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_DAGGER,                      ItemType.Sword,       unique_base_item.UITYPE_NONE,        "Dagger",                      null,           1,          16,       1,       4,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       20 ),
        /*IDI_RUNEBOMB   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_RUNE_BOMB,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Rune Bomb",                   null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_THEODORE   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_THEODORE,                    ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Theodore",                    null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_AURIC      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_AMULET,      item_cursor_graphic.ICURS_AURIC_AMULET,                ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Auric Amulet",                null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_AURIC,     spell_id.SPL_NULL,        false,      100 ),
        /*IDI_NOTE1      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_TORN_NOTE_1,                 ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Torn Note 1",                 null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_NOTE2      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_TORN_NOTE_2,                 ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Torn Note 2",                 null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_NOTE3      */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_TORN_NOTE_3,                 ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Torn Note 3",                 null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_FULLNOTE   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_RECONSTRUCTED_NOTE,          ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Reconstructed Note",          null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NOTE,      spell_id.SPL_NULL,        true,         0 ),
        /*IDI_BROWNSUIT  */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BROWN_SUIT,                  ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Brown Suit",                  null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*IDI_GREYSUIT   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_QUEST,  item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_GREY_SUIT,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Grey Suit",                   null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_CAP,                         ItemType.Helm,        unique_base_item.UITYPE_NONE,        "Cap",                         "Cap",          1,          15,       0,       0,      1,      3,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       15 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_SKULL_CAP,                   ItemType.Helm,        unique_base_item.UITYPE_SKULLCAP,    "Skull Cap",                   "Cap",          4,          20,       0,       0,      2,      4,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       25 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_HELM,                        ItemType.Helm,        unique_base_item.UITYPE_HELM,        "Helm",                        "Helm",         8,          30,       0,       0,      4,      6,      25,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       40 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_FULL_HELM,                   ItemType.Helm,        unique_base_item.UITYPE_NONE,        "Full Helm",                   "Helm",        12,          35,       0,       0,      6,      8,      35,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       90 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_CROWN,                       ItemType.Helm,        unique_base_item.UITYPE_CROWN,       "Crown",                       "Crown",       16,          40,       0,       0,      8,     12,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_HELM,        item_cursor_graphic.ICURS_GREAT_HELM,                  ItemType.Helm,        unique_base_item.UITYPE_GREATHELM,   "Great Helm",                  "Helm",        20,          60,       0,       0,     10,     15,      50,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      400 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_CAPE,                        ItemType.LightArmor,  unique_base_item.UITYPE_CAPE,        "Cape",                        "Cape",         1,          12,       0,       0,      1,      5,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       10 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_RAGS,                        ItemType.LightArmor,  unique_base_item.UITYPE_RAGS,        "Rags",                        "Rags",         1,           6,       0,       0,      2,      6,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        5 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_CLOAK,                       ItemType.LightArmor,  unique_base_item.UITYPE_CLOAK,       "Cloak",                       "Cloak",        2,          18,       0,       0,      3,      7,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       40 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_ROBE,                        ItemType.LightArmor,  unique_base_item.UITYPE_ROBE,        "Robe",                        "Robe",         3,          24,       0,       0,      4,      7,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       75 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_QUILTED_ARMOR,               ItemType.LightArmor,  unique_base_item.UITYPE_NONE,        "Quilted Armor",               "Armor",        4,          30,       0,       0,      7,     10,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_LEATHER_ARMOR,               ItemType.LightArmor,  unique_base_item.UITYPE_LEATHARMOR,  "Leather Armor",               "Armor",        6,          35,       0,       0,     10,     13,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      300 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_HARD_LEATHER_ARMOR,          ItemType.LightArmor,  unique_base_item.UITYPE_NONE,        "Hard Leather Armor",          "Armor",        7,          40,       0,       0,     11,     14,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      450 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_STUDDED_LEATHER_ARMOR,       ItemType.LightArmor,  unique_base_item.UITYPE_STUDARMOR,   "Studded Leather Armor",       "Armor",        9,          45,       0,       0,     15,     17,      20,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      700 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_RING_MAIL,                   ItemType.MediumArmor, unique_base_item.UITYPE_NONE,        "Ring Mail",                   "Mail",        11,          50,       0,       0,     17,     20,      25,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      900 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_CHAIN_MAIL,                  ItemType.MediumArmor, unique_base_item.UITYPE_CHAINMAIL,   "Chain Mail",                  "Mail",        13,          55,       0,       0,     18,     22,      30,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     1250 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_SCALE_MAIL,                  ItemType.MediumArmor, unique_base_item.UITYPE_NONE,        "Scale Mail",                  "Mail",        15,          60,       0,       0,     23,     28,      35,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     2300 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_BREAST_PLATE,                ItemType.HeavyArmor,  unique_base_item.UITYPE_BREASTPLATE, "Breast Plate",                "Plate",       16,          80,       0,       0,     20,     24,      40,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     2800 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_SPLINT_MAIL,                 ItemType.MediumArmor, unique_base_item.UITYPE_NONE,        "Splint Mail",                 "Mail",        17,          65,       0,       0,     30,     35,      40,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     3250 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_FIELD_PLATE,                 ItemType.HeavyArmor,  unique_base_item.UITYPE_PLATEMAIL,   "Plate Mail",                  "Plate",       19,          75,       0,       0,     42,     50,      60,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     4600 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_FIELD_PLATE,                 ItemType.HeavyArmor,  unique_base_item.UITYPE_NONE,        "Field Plate",                 "Plate",       21,          80,       0,       0,     40,     45,      65,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     5800 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_GOTHIC_PLATE,                ItemType.HeavyArmor,  unique_base_item.UITYPE_NONE,        "Gothic Plate",                "Plate",       23,         100,       0,       0,     50,     60,      80,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     8000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ARMOR,       item_cursor_graphic.ICURS_FULL_PLATE_MAIL,             ItemType.HeavyArmor,  unique_base_item.UITYPE_FULLPLATE,   "Full Plate Mail",             "Plate",       25,          90,       0,       0,     60,     75,      90,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     6500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_BUCKLER,                     ItemType.Shield,      unique_base_item.UITYPE_BUCKLER,     "Buckler",                     "Shield",       1,          16,       0,       0,      1,      5,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       30 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_SMALL_SHIELD,                ItemType.Shield,      unique_base_item.UITYPE_SMALLSHIELD, "Small Shield",                "Shield",       5,          24,       0,       0,      3,      8,      25,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       90 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_LARGE_SHIELD,                ItemType.Shield,      unique_base_item.UITYPE_LARGESHIELD, "Large Shield",                "Shield",       9,          32,       0,       0,      5,     10,      40,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_KITE_SHIELD,                 ItemType.Shield,      unique_base_item.UITYPE_KITESHIELD,  "Kite Shield",                 "Shield",      14,          40,       0,       0,      8,     15,      50,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      400 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_TOWER_SHIELD,                ItemType.Shield,      unique_base_item.UITYPE_GOTHSHIELD,  "Tower Shield",                "Shield",      20,          50,       0,       0,     12,     20,      60,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      850 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_ARMOR,  item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_GOTHIC_SHIELD,               ItemType.Shield,      unique_base_item.UITYPE_GOTHSHIELD,  "Gothic Shield",               "Shield",      23,          60,       0,       0,     14,     18,      80,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     2300 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_HEALING,           ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Healing",           null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_HEAL,      spell_id.SPL_NULL,        true,        50 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_FULL_HEALING,      ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Full Healing",      null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_FULLHEAL,  spell_id.SPL_NULL,        true,       150 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_MANA,              ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Mana",              null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_MANA,      spell_id.SPL_NULL,        true,        50 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_FULL_MANA,         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Full Mana",         null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_FULLMANA,  spell_id.SPL_NULL,        true,       150 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_REJUVENATION,      ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Rejuvenation",      null,           3,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_REJUV,     spell_id.SPL_NULL,        true,       120 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_POTION_OF_FULL_REJUVENATION, ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Potion of Full Rejuvenation", null,           7,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_FULLREJUV, spell_id.SPL_NULL,        true,       600 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_OIL,                         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Blacksmith Oil",              null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_OILBSMTH,  spell_id.SPL_NULL,        true,       100 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_OIL,                         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Oil of Accuracy",             null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_OILACC,    spell_id.SPL_NULL,        true,       500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_OIL,                         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Oil of Sharpness",            null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_OILSHARP,  spell_id.SPL_NULL,        true,       500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_OIL,                         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Oil",                         null,          10,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_OILOF,     spell_id.SPL_NULL,        true,         0 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_ELIXIR_OF_STRENGTH,          ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Elixir of Strength",          null,          15,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_ELIXSTR,   spell_id.SPL_NULL,        true,      5000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_ELIXIR_OF_MAGIC,             ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Elixir of Magic",             null,          15,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_ELIXMAG,   spell_id.SPL_NULL,        true,      5000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_ELIXIR_OF_DEXTERITY,         ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Elixir of Dexterity",         null,          15,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_ELIXDEX,   spell_id.SPL_NULL,        true,      5000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_ELIXIR_OF_VITALITY,          ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Elixir of Vitality",          null,          20,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_ELIXVIT,   spell_id.SPL_NULL,        true,      5000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Healing",           null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_HEAL,        true,        50 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Search",            null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_SEARCH,      true,        50 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Lightning",         null,           4,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_LIGHTNING,   true,       150 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Identify",          null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_IDENTIFY,    true,       100 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Resurrect",         null,           1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_RESURRECT,   true,       250 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Fire Wall",         null,           4,           0,       0,       0,      0,      0,       0,      17,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_FIREWALL,    true,       400 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Inferno",           null,           1,           0,       0,       0,      0,      0,       0,      19,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_FLAME,       true,       100 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Town Portal",       null,           4,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_TOWN,        true,       200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Flash",             null,           6,           0,       0,       0,      0,      0,       0,      21,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_FLASH,       true,       500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Infravision",       null,           8,           0,       0,       0,      0,      0,       0,      23,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_INFRA,       true,       600 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Phasing",           null,           6,           0,       0,       0,      0,      0,       0,      25,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_RNDTELEPORT, true,       200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Mana Shield",       null,           8,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_MANASHIELD,  true,      1200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Flame Wave",        null,          10,           0,       0,       0,      0,      0,       0,      29,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_WAVE,        true,       650 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Fireball",          null,           8,           0,       0,       0,      0,      0,       0,      31,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_FIREBALL,    true,       300 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Stone Curse",       null,           6,           0,       0,       0,      0,      0,       0,      33,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_STONE,       true,       800 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Chain Lightning",   null,          10,           0,       0,       0,      0,      0,       0,      35,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_CHAIN,       true,       750 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Guardian",          null,          12,           0,       0,       0,      0,      0,       0,      47,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_GUARDIAN,    true,       950 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Non Item",                    null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Nova",              null,          14,           0,       0,       0,      0,      0,       0,      57,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_NOVA,        true,      1300 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Golem",             null,          10,           0,       0,       0,      0,      0,       0,      51,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_GOLEM,       true,      1100 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of None",              null,          99,           0,       0,       0,      0,      0,       0,      61,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLLT,   spell_id.SPL_NULL,        true,      1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Teleport",          null,          14,           0,       0,       0,      0,      0,       0,      81,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_TELEPORT,    true,      3000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_SCROLL_OF,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Scroll of Apocalypse",        null,          22,           0,       0,       0,      0,      0,       0,     117,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_SCROLL,    spell_id.SPL_APOCA,       true,      2000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BOOK_BLUE,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Book of ",                    null,           2,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_BOOK,      spell_id.SPL_NULL,        true,         0 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BOOK_BLUE,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Book of ",                    null,           8,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_BOOK,      spell_id.SPL_NULL,        true,         0 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BOOK_BLUE,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Book of ",                    null,          14,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_BOOK,      spell_id.SPL_NULL,        true,         0 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_BOOK_BLUE,                   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Book of ",                    null,          20,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_BOOK,      spell_id.SPL_NULL,        true,         0 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_DAGGER,                      ItemType.Sword,       unique_base_item.UITYPE_DAGGER,      "Dagger",                      "Dagger",       1,          16,       1,       4,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       60 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_SHORT_SWORD,                 ItemType.Sword,       unique_base_item.UITYPE_NONE,        "Short Sword",                 "Sword",        1,          24,       2,       6,      0,      0,      18,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      120 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_FALCHION,                    ItemType.Sword,       unique_base_item.UITYPE_FALCHION,    "Falchion",                    "Sword",        2,          20,       4,       8,      0,      0,      30,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      250 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_SCIMITAR,                    ItemType.Sword,       unique_base_item.UITYPE_SCIMITAR,    "Scimitar",                    "Sword",        4,          28,       3,       7,      0,      0,      23,       0,      23, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_CLAYMORE,                    ItemType.Sword,       unique_base_item.UITYPE_CLAYMORE,    "Claymore",                    "Sword",        5,          36,       1,      12,      0,      0,      35,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      450 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_BLADE,                       ItemType.Sword,       unique_base_item.UITYPE_NONE,        "Blade",                       "Blade",        4,          30,       3,       8,      0,      0,      25,       0,      30, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      280 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_SABRE,                       ItemType.Sword,       unique_base_item.UITYPE_SABRE,       "Sabre",                       "Sabre",        1,          45,       1,       8,      0,      0,      17,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      170 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_LONG_SWORD,                  ItemType.Sword,       unique_base_item.UITYPE_LONGSWR,     "Long Sword",                  "Sword",        6,          40,       2,      10,      0,      0,      30,       0,      30, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      350 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_BROAD_SWORD,                 ItemType.Sword,       unique_base_item.UITYPE_BROADSWR,    "Broad Sword",                 "Sword",        8,          50,       4,      12,      0,      0,      40,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      750 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_BASTARD_SWORD,               ItemType.Sword,       unique_base_item.UITYPE_BASTARDSWR,  "Bastard Sword",               "Sword",       10,          60,       6,      15,      0,      0,      50,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_TWO_HANDED_SWORD,            ItemType.Sword,       unique_base_item.UITYPE_TWOHANDSWR,  "Two-Handed Sword",            "Sword",       14,          75,       8,      16,      0,      0,      65,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     1800 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_GREAT_SWORD,                 ItemType.Sword,       unique_base_item.UITYPE_GREATSWR,    "Great Sword",                 "Sword",       17,         100,      10,      20,      0,      0,      75,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     3000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SMALL_AXE,                   ItemType.Axe,         unique_base_item.UITYPE_SMALLAXE,    "Small Axe",                   "Axe",          2,          24,       2,      10,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      150 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_AXE,                         ItemType.Axe,         unique_base_item.UITYPE_NONE,        "Axe",                         "Axe",          4,          32,       4,      12,      0,      0,      22,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      450 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_LARGE_AXE,                   ItemType.Axe,         unique_base_item.UITYPE_LARGEAXE,    "Large Axe",                   "Axe",          6,          40,       6,      16,      0,      0,      30,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      750 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_BROAD_AXE,                   ItemType.Axe,         unique_base_item.UITYPE_BROADAXE,    "Broad Axe",                   "Axe",          8,          50,       8,      20,      0,      0,      50,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_BATTLE_AXE,                  ItemType.Axe,         unique_base_item.UITYPE_BATTLEAXE,   "Battle Axe",                  "Axe",         10,          60,      10,      25,      0,      0,      65,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     1500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_GREAT_AXE,                   ItemType.Axe,         unique_base_item.UITYPE_GREATAXE,    "Great Axe",                   "Axe",         12,          75,      12,      30,      0,      0,      80,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     2500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_MACE,                        ItemType.Mace,        unique_base_item.UITYPE_MACE,        "Mace",                        "Mace",         2,          32,       1,       8,      0,      0,      16,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_MORNING_STAR,                ItemType.Mace,        unique_base_item.UITYPE_MORNSTAR,    "Morning Star",                "Mace",         3,          40,       1,      10,      0,      0,      26,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      300 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_WAR_HAMMER,                  ItemType.Mace,        unique_base_item.UITYPE_WARHAMMER,   "War Hammer",                  "Hammer",       5,          50,       5,       9,      0,      0,      40,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      600 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_SPIKED_CLUB,                 ItemType.Mace,        unique_base_item.UITYPE_SPIKCLUB,    "Spiked Club",                 "Club",         4,          20,       3,       6,      0,      0,      18,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      225 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_CLUB,                        ItemType.Mace,        unique_base_item.UITYPE_SPIKCLUB,    "Club",                        "Club",         1,          20,       1,       6,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,       20 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_ONEHAND,     item_cursor_graphic.ICURS_FLAIL,                       ItemType.Mace,        unique_base_item.UITYPE_FLAIL,       "Flail",                       "Flail",        7,          36,       2,      12,      0,      0,      30,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_MAUL,                        ItemType.Mace,        unique_base_item.UITYPE_MAUL,        "Maul",                        "Maul",        10,          50,       6,      20,      0,      0,      55,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      900 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_BOW,                   ItemType.Bow,         unique_base_item.UITYPE_SHORTBOW,    "Short Bow",                   "Bow",          1,          30,       1,       4,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      100 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_HUNTERS_BOW,                 ItemType.Bow,         unique_base_item.UITYPE_HUNTBOW,     "Hunter's Bow",                "Bow",          3,          40,       2,       5,      0,      0,      20,       0,      35, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      350 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_HUNTERS_BOW,                 ItemType.Bow,         unique_base_item.UITYPE_LONGBOW,     "Long Bow",                    "Bow",          5,          35,       1,       6,      0,      0,      25,       0,      30, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      250 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_COMPOSITE_BOW,               ItemType.Bow,         unique_base_item.UITYPE_COMPBOW,     "Composite Bow",               "Bow",          7,          45,       3,       6,      0,      0,      25,       0,      40, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      600 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_BATTLE_BOW,            ItemType.Bow,         unique_base_item.UITYPE_NONE,        "Short Battle Bow",            "Bow",          9,          45,       3,       7,      0,      0,      30,       0,      50, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,      750 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_LONG_BATTLE_BOW,             ItemType.Bow,         unique_base_item.UITYPE_BATTLEBOW,   "Long Battle Bow",             "Bow",         11,          50,       1,      10,      0,      0,      30,       0,      60, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_WAR_BOW,               ItemType.Bow,         unique_base_item.UITYPE_NONE,        "Short War Bow",               "Bow",         15,          55,       4,       8,      0,      0,      35,       0,      70, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     1500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_DOUBLE,  item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_LONG_WAR_BOW,                ItemType.Bow,         unique_base_item.UITYPE_WARBOW,      "Long War Bow",                "Bow",         19,          60,       1,      14,      0,      0,      45,       0,      80, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,     2000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_STAFF,                 ItemType.Staff,       unique_base_item.UITYPE_SHORTSTAFF,  "Short Staff",                 "Staff",        1,          25,       2,       4,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_STAFF,     spell_id.SPL_NULL,        false,       30 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_LONG_STAFF,                  ItemType.Staff,       unique_base_item.UITYPE_LONGSTAFF,   "Long Staff",                  "Staff",        4,          35,       4,       8,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_STAFF,     spell_id.SPL_NULL,        false,      100 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_COMPOSITE_STAFF,             ItemType.Staff,       unique_base_item.UITYPE_COMPSTAFF,   "Composite Staff",             "Staff",        6,          45,       5,      10,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_STAFF,     spell_id.SPL_NULL,        false,      500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_STAFF,                 ItemType.Staff,       unique_base_item.UITYPE_QUARSTAFF,   "Quarter Staff",               "Staff",        9,          55,       6,      12,      0,      0,      20,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_STAFF,     spell_id.SPL_NULL,        false,     1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_WAR_STAFF,                   ItemType.Staff,       unique_base_item.UITYPE_WARSTAFF,    "War Staff",                   "Staff",       12,          75,       8,      16,      0,      0,      30,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_STAFF,     spell_id.SPL_NULL,        false,     1500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_RING,        item_cursor_graphic.ICURS_RING,                        ItemType.Ring,        unique_base_item.UITYPE_RING,        "Ring",                        "Ring",         5,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_RING,      spell_id.SPL_NULL,        false,     1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_RING,        item_cursor_graphic.ICURS_RING,                        ItemType.Ring,        unique_base_item.UITYPE_RING,        "Ring",                        "Ring",        10,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_RING,      spell_id.SPL_NULL,        false,     1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_RING,        item_cursor_graphic.ICURS_RING,                        ItemType.Ring,        unique_base_item.UITYPE_RING,        "Ring",                        "Ring",        15,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_RING,      spell_id.SPL_NULL,        false,     1000 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_AMULET,      item_cursor_graphic.ICURS_AMULET,                      ItemType.Amulet,      unique_base_item.UITYPE_AMULET,      "Amulet",                      "Amulet",       8,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_AMULET,    spell_id.SPL_NULL,        false,     1200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_AMULET,      item_cursor_graphic.ICURS_AMULET,                      ItemType.Amulet,      unique_base_item.UITYPE_AMULET,      "Amulet",                      "Amulet",      16,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_AMULET,    spell_id.SPL_NULL,        false,     1200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_RUNE_OF_FIRE,                ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Rune of Fire",                "Rune",         1,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_RUNEF,     spell_id.SPL_NULL,         true,      100 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_RUNE_OF_LIGHTNING,           ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Rune of Lightning",           "Rune",         3,           0,       0,       0,      0,      0,       0,      13,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_RUNEL,     spell_id.SPL_NULL,         true,      200 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_GREATER_RUNE_OF_FIRE,        ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Greater Rune of Fire",        "Rune",         7,           0,       0,       0,      0,      0,       0,      42,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_GR_RUNEF,  spell_id.SPL_NULL,         true,      400 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_GREATER_RUNE_OF_LIGHTNING,   ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Greater Rune of Lightning",   "Rune",         7,           0,       0,       0,      0,      0,       0,      42,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_GR_RUNEL,  spell_id.SPL_NULL,         true,      500 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_REGULAR, item_class.ICLASS_MISC,   item_equip_type.ILOC_UNEQUIPABLE, item_cursor_graphic.ICURS_RUNE_OF_STONE,               ItemType.Misc,        unique_base_item.UITYPE_NONE,        "Rune of Stone",               "Rune",         7,           0,       0,       0,      0,      0,       0,      25,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_RUNES,     spell_id.SPL_NULL,         true,      300 ),
        /*IDI_SORCERER   */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_WEAPON, item_equip_type.ILOC_TWOHAND,     item_cursor_graphic.ICURS_SHORT_STAFF,                 ItemType.Staff,       unique_base_item.UITYPE_NONE,        "Short Staff of Charged Bolt", null,           1,          25,       2,       4,      0,      0,       0,      20,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_STAFF,     spell_id.SPL_CBOLT,       false,      520 ),
        /*               */ new ItemData(  item_drop_rate.IDROP_NEVER,   item_class.ICLASS_NONE,   item_equip_type.ILOC_INVALID,     item_cursor_graphic.ICURS_POTION_OF_FULL_MANA,         ItemType.Misc,        unique_base_item.UITYPE_NONE,        null,                          null,           0,           0,       0,       0,      0,      0,       0,       0,       0, ItemSpecialEffect.None,                          item_misc_id.IMISC_NONE,      spell_id.SPL_NULL,        false,        0 ),
            // clang-format on
        };
    }
}
